### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by CMJaefarsadikh** [botble/docs#1]
i tried to create new page but i got error ..
Trying to get property of non-object (View: C:\wamp64\www\botble_new\plugins\language\resources\views\language-box.blade.php) (View: C:\wamp64\www\botble_new\plugins\language\resources\views\language-box.blade.php)

**Comment by sangnguyenplus** [comment]
Hi @CMJaefarsadikh,
Please add bellow code after `plugins/language/src/Providers/LanguageServiceProvider.php:181`
```
if (!$current_language) {
       $current_language = Language::getDefaultLanguage(['flag', 'name', 'code']);
}
```
![Image](http://i.prntscr.com/pkQ_D_LkRCqdmhaJcfVi4Q.png)

Thanks!

**Comment by CMJaefarsadikh** [comment]
thank you sir fixed

**Comment by CMJaefarsadikh** [comment]
![botblenew](https://user-images.githubusercontent.com/24778052/28873540-c452d96c-77ab-11e7-900c-c022350ba68a.jpg)
